# permissions for end users to edit cnfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: project
    app.kubernetes.io/managed-by: kustomize
  name: cnf-editor-role
rules:
- apiGroups:
  - apps.example.com
  resources:
  - cnfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.example.com
  resources:
  - cnfs/status
  verbs:
  - get
